### ISSUE TITLE
Not compatible with beta 8

### ISSUE THREAD

**Issue by HLFH** [hyn/flarum-guardian#4]
- flagrow/flarum-ext-guardian extension version: master
- flarum version: 0.1.0-beta.8
---

I got the error Uncaught TypeError: Cannot read property 'default' of undefined in JS Console and nothing is loading besides the header.

**Comment by luceos** [comment]
@HLFH 

- beta 8 isn't released yet
- this extension will not be continued, there are better alternatives that offer a users list; the other feature it offered was showing an ip address which has been added to core for a while.

A new guardian is underway as premium extension for beta 8.
